USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_default
USEMODULE += gnrc_netdev_default
#USEMODULE += gnrc_sock_async
USEMODULE += gnrc_sock_udp
USEMODULE += gnrc_udp
USEMODULE += posix_inet
USEMODULE += sock_dns
